import apiClient from './apiClient';
import { Category, Service } from '@/types/models';

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'plumbing',
    name: 'Plumbing',
    iconUrl: 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?auto=format&fit=crop&w=600&q=80',
    isActive: true,
    displayOrder: 1,
  },
  {
    id: 'electrician',
    name: 'Electrician',
    iconUrl: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=600&q=80',
    isActive: true,
    displayOrder: 2,
  },
  {
    id: 'carpentry',
    name: 'Carpentry',
    iconUrl: 'https://images.unsplash.com/photo-1530124566582-a618bc2615dc?auto=format&fit=crop&w=600&q=80',
    isActive: true,
    displayOrder: 3,
  },
  {
    id: 'ac-repair',
    name: 'AC Repair',
    iconUrl: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=600&q=80',
    isActive: true,
    displayOrder: 4,
  },
  {
    id: 'home-cleaning',
    name: 'Home Cleaning',
    iconUrl: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=600&q=80',
    isActive: true,
    displayOrder: 5,
  },
  {
    id: 'painting',
    name: 'Painting',
    iconUrl: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=600&q=80',
    isActive: true,
    displayOrder: 6,
  },
  {
    id: 'pest-control',
    name: 'Pest Control',
    iconUrl: 'https://images.unsplash.com/photo-1584483766114-2cea6facdf57?auto=format&fit=crop&w=600&q=80',
    isActive: true,
    displayOrder: 7,
  },
  {
    id: 'appliance-repair',
    name: 'Appliance Repair',
    iconUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
    isActive: true,
    displayOrder: 8,
  },
  {
    id: 'gardening',
    name: 'Gardening',
    iconUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=600&q=80',
    isActive: true,
    displayOrder: 9,
  },
  {
    id: 'locksmith',
    name: 'Locksmith',
    iconUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=600&q=80',
    isActive: true,
    displayOrder: 10,
  },
  {
    id: 'water-tank-cleaning',
    name: 'Water Tank Cleaning',
    iconUrl: 'https://images.unsplash.com/photo-1542013936693-884638332954?auto=format&fit=crop&w=600&q=80',
    isActive: true,
    displayOrder: 11,
  },
  {
    id: 'general-home-repairs',
    name: 'General Home Repairs',
    iconUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
    isActive: true,
    displayOrder: 12,
  },
];

export const MOCK_SERVICES: Service[] = [
  // ── PLUMBING ─────────────────────────────────────────────────────────────────
  {
    id: 'svc-plumb-1',
    categoryId: 'plumbing',
    name: 'Tap & Basin Leak Repair',
    description: 'Fix dripping faucets, mixer valves, clogged drainage traps, sink connection pipes, and concealed line leaks.',
    price: 299,
    originalPrice: 499,
    rating: 4.89,
    reviews: 4210,
    badge: 'Best Seller',
    estimatedDurationMinutes: 30,
    imageUrl: 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&w=800&q=80',
    ],
    inclusions: ['Spindle & washer replacement', 'Teflon thread leak sealing', 'Waste pipe alignment & testing', '30-day warranty'],
    exclusions: ['Cost of brand new brass taps'],
    isActive: true,
  },
  {
    id: 'svc-plumb-2',
    categoryId: 'plumbing',
    name: 'Toilet Flush & Jet Spray Fitting',
    description: 'Complete inspection and repair of cistern siphon, ball valve, health faucet, angle valve, and jet spray.',
    price: 349,
    originalPrice: 599,
    rating: 4.85,
    reviews: 2890,
    badge: 'Popular',
    estimatedDurationMinutes: 45,
    imageUrl: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Flush tank valve adjustment', 'Jet spray hose installation', 'Leak testing', '30-day warranty'],
    exclusions: ['Ceramic commode replacement'],
    isActive: true,
  },
  {
    id: 'svc-plumb-3',
    categoryId: 'plumbing',
    name: 'Water Pipe Leakage & Pressure Check',
    description: 'Diagnose and fix concealed pipe leaks, CPVC/PVC joint failures, seepage through walls, and water pressure drop issues.',
    price: 599,
    originalPrice: 999,
    rating: 4.87,
    reviews: 1650,
    badge: 'Specialist',
    estimatedDurationMinutes: 60,
    imageUrl: 'https://images.unsplash.com/photo-1542013936693-884638332954?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Pressure gauge diagnostics', 'Joint re-sealing', 'Concealed leak trace', '30-day warranty'],
    exclusions: ['Wall cutting & patch plastering'],
    isActive: true,
  },
  {
    id: 'svc-plumb-4',
    categoryId: 'plumbing',
    name: 'Washbasin & Kitchen Sink Installation',
    description: 'New counter-top or under-mount basin fitting, P-trap assembly, waste pipe connection, and silicon sealing.',
    price: 499,
    originalPrice: 799,
    rating: 4.82,
    reviews: 980,
    badge: 'Installation',
    estimatedDurationMinutes: 60,
    imageUrl: 'https://images.unsplash.com/photo-1556909114-44e3e9699e2b?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Basin mounting & leveling', 'Waste fitting & P-trap', 'Silicon waterproof sealing', '30-day warranty'],
    exclusions: ['New basin / tap purchase'],
    isActive: true,
  },
  {
    id: 'svc-plumb-5',
    categoryId: 'plumbing',
    name: 'Drain Unclogging & Blockage Removal',
    description: 'Heavy-duty snake clearing of kitchen sink, washbasin, floor drain, and main stack blockages with enzymatic flush.',
    price: 399,
    originalPrice: 699,
    rating: 4.91,
    reviews: 3200,
    badge: 'Emergency Fix',
    estimatedDurationMinutes: 45,
    imageUrl: 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Drain snake clearance', 'Enzymatic cleaning liquid', 'Flow speed verification', '30-day warranty'],
    exclusions: ['Main sewer excavation'],
    isActive: true,
  },

  // ── ELECTRICIAN ───────────────────────────────────────────────────────────────
  {
    id: 'svc-elec-1',
    categoryId: 'electrician',
    name: 'Switch, Socket & MCB Replacement',
    description: 'Replace faulty modular switches, burned power sockets, tripping MCB circuit breakers, and fuse units.',
    price: 199,
    originalPrice: 349,
    rating: 4.88,
    reviews: 5120,
    badge: 'Most Booked',
    estimatedDurationMinutes: 30,
    imageUrl: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Voltage & load testing', 'Modular switch fitting', 'Earthing check', '30-day warranty'],
    exclusions: ['Cost of new modular switch plates'],
    isActive: true,
  },
  {
    id: 'svc-elec-2',
    categoryId: 'electrician',
    name: 'Ceiling Fan Installation & Repair',
    description: 'New fan hanging with heavy-duty rod, regulator connection, capacitor replacement, and wobble balancing.',
    price: 249,
    originalPrice: 449,
    rating: 4.84,
    reviews: 3870,
    badge: 'Popular',
    estimatedDurationMinutes: 35,
    imageUrl: 'https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Ceiling hook load testing', 'Blade balancing', 'Speed test', '30-day warranty'],
    exclusions: ['New fan appliance purchase'],
    isActive: true,
  },
  {
    id: 'svc-elec-3',
    categoryId: 'electrician',
    name: 'Inverter & Complete Wiring Check',
    description: 'Home inverter/UPS inspection, battery terminal cleaning, wiring fault trace, load balancing, and safety audit.',
    price: 499,
    originalPrice: 799,
    rating: 4.86,
    reviews: 1420,
    badge: 'Safety Audit',
    estimatedDurationMinutes: 60,
    imageUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Battery terminal inspection', 'Load balancing', 'Wiring fault trace', '30-day warranty'],
    exclusions: ['New inverter battery'],
    isActive: true,
  },
  {
    id: 'svc-elec-4',
    categoryId: 'electrician',
    name: 'LED Concealed Light & Chandelier Fitting',
    description: 'Precision mounting of LED downlights, cove lighting strips, false ceiling lights, and decorative chandeliers.',
    price: 349,
    originalPrice: 599,
    rating: 4.83,
    reviews: 2100,
    badge: 'Home Décor',
    estimatedDurationMinutes: 45,
    imageUrl: 'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?auto=format&fit=crop&w=800&q=80',
    inclusions: ['False ceiling hole cutting', 'Driver wiring', 'Dimmer connection', '30-day warranty'],
    exclusions: ['Cost of LED panels or strips'],
    isActive: true,
  },
  {
    id: 'svc-elec-5',
    categoryId: 'electrician',
    name: 'Geyser & Water Heater Wiring Fix',
    description: 'Safe installation of 15A geyser socket, thermostat check, earthing, pressure relief valve inspection.',
    price: 449,
    originalPrice: 749,
    rating: 4.87,
    reviews: 1880,
    badge: 'Safety',
    estimatedDurationMinutes: 45,
    imageUrl: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=800&q=80',
    inclusions: ['15A dedicated socket fitting', 'Earth leakage check', 'Thermostat testing', '30-day warranty'],
    exclusions: ['New geyser unit purchase'],
    isActive: true,
  },

  // ── CARPENTRY ─────────────────────────────────────────────────────────────────
  {
    id: 'svc-carp-1',
    categoryId: 'carpentry',
    name: 'Door Lock, Handle & Hinge Repair',
    description: 'Expert alignment of sagging wooden doors, deadbolt lock installation, hydraulic closer fitting, and latch adjustments.',
    price: 349,
    originalPrice: 599,
    rating: 4.88,
    reviews: 3540,
    badge: 'Best Seller',
    estimatedDurationMinutes: 45,
    imageUrl: 'https://images.unsplash.com/photo-1530124566582-a618bc2615dc?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Hinge mortise alignment', 'Latch strike plate routing', 'Lock barrel lubrication', '30-day warranty'],
    exclusions: ['Cost of computerized lock set'],
    isActive: true,
  },
  {
    id: 'svc-carp-2',
    categoryId: 'carpentry',
    name: 'Bed & Wardrobe Assembly / Repair',
    description: 'Disassembly, realignment, hydraulic pump replacement, sliding channel tuning, and hinge tightening for modular furniture.',
    price: 599,
    originalPrice: 999,
    rating: 4.85,
    reviews: 2210,
    badge: 'Popular',
    estimatedDurationMinutes: 90,
    imageUrl: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Hydraulic bed lift inspection', 'Drawer slider lubrication', 'Structural bolt tightening', '30-day warranty'],
    exclusions: ['New timber or plywood materials'],
    isActive: true,
  },
  {
    id: 'svc-carp-3',
    categoryId: 'carpentry',
    name: 'Custom Wooden Shelf & Drawer Fixing',
    description: 'Wall-mounted floating shelf, wooden bracket fitting, drawer track replacement, and kitchen cabinet hinge repair.',
    price: 399,
    originalPrice: 699,
    rating: 4.82,
    reviews: 1390,
    badge: 'Custom Work',
    estimatedDurationMinutes: 60,
    imageUrl: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Wall anchor drilling', 'Shelf leveling', 'Load capacity test', '30-day warranty'],
    exclusions: ['Purchase of wood / brackets'],
    isActive: true,
  },
  {
    id: 'svc-carp-4',
    categoryId: 'carpentry',
    name: 'Sliding Door & Window Track Alignment',
    description: 'Re-align warped aluminum/uPVC sliding doors, replace worn wheel rollers, fix window mesh, and seal gaps.',
    price: 449,
    originalPrice: 749,
    rating: 4.80,
    reviews: 1050,
    badge: 'Quick Fix',
    estimatedDurationMinutes: 45,
    imageUrl: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Track cleaning & lubrication', 'Roller wheel replacement', 'Weather seal strip', '30-day warranty'],
    exclusions: ['Full frame replacement'],
    isActive: true,
  },
  {
    id: 'svc-carp-5',
    categoryId: 'carpentry',
    name: 'Furniture Touch-Up & Polish',
    description: 'PU lacquer, wax polish, or oil finish touch-up for scratched, stained, or faded wooden furniture surfaces.',
    price: 499,
    originalPrice: 899,
    rating: 4.78,
    reviews: 870,
    badge: 'Restoration',
    estimatedDurationMinutes: 60,
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Surface sanding', '2-coat PU lacquer', 'Color-match touch-up', '30-day warranty'],
    exclusions: ['Full re-polish of antique pieces'],
    isActive: true,
  },

  // ── AC REPAIR ─────────────────────────────────────────────────────────────────
  {
    id: 'svc-ac-1',
    categoryId: 'ac-repair',
    name: 'AC Deep Service & Jet Clean',
    description: 'Complete split/window AC inspection, high-pressure jet cleaning of indoor and outdoor coils, gas pressure check.',
    price: 499,
    originalPrice: 899,
    rating: 4.91,
    reviews: 8420,
    badge: 'Best Seller',
    estimatedDurationMinutes: 60,
    imageUrl: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Indoor filter deep wash', 'Outdoor jet spray cleaning', 'Gas pressure test', 'Ampere diagnostic', '30-day warranty'],
    exclusions: ['Gas refilling cost', 'Copper pipe replacement'],
    isActive: true,
  },
  {
    id: 'svc-ac-2',
    categoryId: 'ac-repair',
    name: 'AC Foam Jet Deep Cleaning',
    description: 'Specialized 2x foam technology for mold and fungus elimination, restoring factory-level airflow and 30% faster cooling.',
    price: 699,
    originalPrice: 1199,
    rating: 4.89,
    reviews: 5680,
    badge: 'Premium',
    estimatedDurationMinutes: 90,
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    inclusions: ['High pressure active foam spray', 'Deep coil sanitization', 'Anti-bacterial coating', 'Drain unclogging', '30-day warranty'],
    exclusions: ['Spare parts replacement'],
    isActive: true,
  },
  {
    id: 'svc-ac-3',
    categoryId: 'ac-repair',
    name: 'AC Installation & Wall Mounting',
    description: 'New split AC installation with bracket mounting, copper pipe routing, drain pipe laying, and power socket setup.',
    price: 999,
    originalPrice: 1699,
    rating: 4.86,
    reviews: 3210,
    badge: 'Installation',
    estimatedDurationMinutes: 120,
    imageUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80',
    inclusions: ['MS bracket wall mounting', 'Copper pipe routing (up to 3ft)', 'Drain pipe laying', 'Power socket check', '30-day warranty'],
    exclusions: ['Additional copper pipe beyond 3ft'],
    isActive: true,
  },
  {
    id: 'svc-ac-4',
    categoryId: 'ac-repair',
    name: 'AC Gas Leak Detection & Top-Up',
    description: 'Nitrogen pressure test, brazing/soldering leak fix, and 100% genuine R32/R410A refrigerant recharge.',
    price: 1899,
    originalPrice: 2999,
    rating: 4.84,
    reviews: 2140,
    badge: 'Specialist',
    estimatedDurationMinutes: 90,
    imageUrl: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Nitrogen leak detection', 'Leak brazing/sealing', 'Factory gas refill', 'Cooling temperature test', '30-day warranty'],
    exclusions: ['PCB board circuit repair'],
    isActive: true,
  },
  {
    id: 'svc-ac-5',
    categoryId: 'ac-repair',
    name: 'Split AC Uninstallation & Safe Packing',
    description: 'Safe gas recovery, indoor/outdoor unit dismounting, copper pipe cap sealing, and secure packing for transport.',
    price: 499,
    originalPrice: 799,
    rating: 4.80,
    reviews: 1380,
    badge: 'Relocation',
    estimatedDurationMinutes: 60,
    imageUrl: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Gas recovery (pump-down)', 'Bracket dismounting', 'Pipe end cap sealing', 'Safe unit packing'],
    exclusions: ['Reinstallation at new location'],
    isActive: true,
  },

  // ── HOME CLEANING ─────────────────────────────────────────────────────────────
  {
    id: 'svc-clean-1',
    categoryId: 'home-cleaning',
    name: 'Full Home Deep Cleaning',
    description: 'Comprehensive top-to-bottom sanitization of all rooms, kitchen degreasing, bathroom scrubbing, balcony wash, and floor buffing.',
    price: 1499,
    originalPrice: 2499,
    rating: 4.92,
    reviews: 9810,
    badge: 'Top Choice',
    estimatedDurationMinutes: 180,
    imageUrl: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80',
    inclusions: ['All rooms ceiling cobweb removal', 'Floor machine scrub', 'Window tracks & glass wipe', 'Bathroom disinfection', '30-day warranty'],
    exclusions: ['Curtain laundry'],
    isActive: true,
  },
  {
    id: 'svc-clean-2',
    categoryId: 'home-cleaning',
    name: 'Kitchen Deep Sanitization & Degreasing',
    description: 'Intense steam descaling of chimney, stove burners, tile backsplashes, cabinet exteriors, and oil trap degreasing.',
    price: 799,
    originalPrice: 1399,
    rating: 4.88,
    reviews: 4320,
    badge: 'Popular',
    estimatedDurationMinutes: 90,
    imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Chimney baffle filter wash', 'Stove knob & burner descale', 'Sink & tile polishing', '30-day warranty'],
    exclusions: ['Inside refrigerator cleaning'],
    isActive: true,
  },
  {
    id: 'svc-clean-3',
    categoryId: 'home-cleaning',
    name: 'Bathroom & Tile Acid Descaling',
    description: 'Removes years of stubborn hard water yellow stains, limescale, and tile grout grime from all surfaces.',
    price: 499,
    originalPrice: 899,
    rating: 4.87,
    reviews: 5670,
    badge: 'Hygiene Pro',
    estimatedDurationMinutes: 75,
    imageUrl: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Eco-friendly descaling acid treatment', 'Grout scrubbing', 'Mirror & chrome polish', 'WC sanitization', '30-day warranty'],
    exclusions: ['Tile re-grouting / masonry'],
    isActive: true,
  },
  {
    id: 'svc-clean-4',
    categoryId: 'home-cleaning',
    name: 'Sofa & Upholstery Shampooing (3-Seater)',
    description: 'Mechanized injection-extraction deep foam wash to remove spills, sweat odor, and dust mites from fabric sofas.',
    price: 699,
    originalPrice: 1199,
    rating: 4.85,
    reviews: 3140,
    badge: 'Fabric Care',
    estimatedDurationMinutes: 60,
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Dry industrial vacuuming', 'Foam shampoo scrubbing', 'High-suction moisture extraction', 'Deodorizing spray', '30-day warranty'],
    exclusions: ['Leather sofa polish (separate)'],
    isActive: true,
  },
  {
    id: 'svc-clean-5',
    categoryId: 'home-cleaning',
    name: 'Balcony & Window Pressure Wash',
    description: 'High-pressure jet cleaning of balcony floors, railings, window glass, channel frames, and bird-net mesh.',
    price: 399,
    originalPrice: 699,
    rating: 4.80,
    reviews: 1890,
    badge: 'Quick Fix',
    estimatedDurationMinutes: 45,
    imageUrl: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Pressure wash of balcony floor', 'Window glass streak-free clean', 'Channel track vacuuming', '30-day warranty'],
    exclusions: ['Interior window curtain cleaning'],
    isActive: true,
  },

  // ── PAINTING ──────────────────────────────────────────────────────────────────
  {
    id: 'svc-paint-1',
    categoryId: 'painting',
    name: '1 Room Express Wall Painting',
    description: '2 coats of premium washable interior emulsion, crack filling, sanding, and floor masking for a crisp new look.',
    price: 1999,
    originalPrice: 3499,
    rating: 4.90,
    reviews: 3280,
    badge: 'Express',
    estimatedDurationMinutes: 240,
    imageUrl: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Floor & furniture plastic masking', 'Putty touch-up & crack filling', '2 coats emulsion paint', 'Post-paint cleanup', '1-year warranty'],
    exclusions: ['Major plaster repair'],
    isActive: true,
  },
  {
    id: 'svc-paint-2',
    categoryId: 'painting',
    name: 'Wall Putty & Waterproofing Seepage Fix',
    description: 'Dr. Fixit polymer waterproofing membrane + putty coat application to stop seepage, dampness, and efflorescence.',
    price: 899,
    originalPrice: 1599,
    rating: 4.86,
    reviews: 1740,
    badge: 'Waterproof',
    estimatedDurationMinutes: 180,
    imageUrl: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Seepage area assessment', 'Dr. Fixit membrane coat', 'White cement putty finish', '2-year waterproof warranty'],
    exclusions: ['Wall tile removal'],
    isActive: true,
  },
  {
    id: 'svc-paint-3',
    categoryId: 'painting',
    name: 'Ceiling Whitewash & Primer Coat',
    description: 'Smooth ceiling whitewash with acrylic primer, stain cover coat, and seamless finish for all room sizes.',
    price: 799,
    originalPrice: 1299,
    rating: 4.83,
    reviews: 1120,
    badge: 'Refresh',
    estimatedDurationMinutes: 180,
    imageUrl: 'https://images.unsplash.com/photo-1582582621959-48d27397dc69?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Stain-block primer', 'Smooth ceiling putty coat', '2 coats whitewash', 'Cleanup included', '1-year warranty'],
    exclusions: ['Chandelier dismounting'],
    isActive: true,
  },
  {
    id: 'svc-paint-4',
    categoryId: 'painting',
    name: 'Texture Accent Wall Designer Paint',
    description: 'Trendy Italian texture, Venetian plaster, or geometric tape art for one accent wall to transform a room.',
    price: 2499,
    originalPrice: 3999,
    rating: 4.88,
    reviews: 890,
    badge: 'Premium Design',
    estimatedDurationMinutes: 300,
    imageUrl: 'https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Pattern consultation', 'Base coat + 2 texture coats', 'Design stenciling', 'Sealer coat', '1-year warranty'],
    exclusions: ['Furniture repositioning'],
    isActive: true,
  },

  // ── PEST CONTROL ──────────────────────────────────────────────────────────────
  {
    id: 'svc-pest-1',
    categoryId: 'pest-control',
    name: 'Cockroach & Ant Gel Treatment',
    description: 'Odorless Bayer herbal gel baiting in kitchen cabinets, drain crevices, electrical boxes, plus perimeter spray.',
    price: 699,
    originalPrice: 1099,
    rating: 4.87,
    reviews: 6540,
    badge: 'Best Seller',
    estimatedDurationMinutes: 45,
    imageUrl: 'https://images.unsplash.com/photo-1584483766114-2cea6facdf57?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Odorless gel application', 'Drain perimeter spray', 'Non-toxic pet friendly', '90-day guarantee'],
    exclusions: ['Emptying kitchen cabinets not required'],
    isActive: true,
  },
  {
    id: 'svc-pest-2',
    categoryId: 'pest-control',
    name: 'Bed Bug Elimination Treatment',
    description: 'Steam heat + Bifenthrin spray treatment for mattresses, sofa seams, headboards, and skirting boards.',
    price: 1199,
    originalPrice: 1999,
    rating: 4.85,
    reviews: 2890,
    badge: 'Specialized',
    estimatedDurationMinutes: 90,
    imageUrl: 'https://images.unsplash.com/photo-1584483766114-2cea6facdf57?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Steam heat treatment', 'Chemical spray', 'Follow-up visit', '90-day guarantee'],
    exclusions: ['Mattress disposal'],
    isActive: true,
  },
  {
    id: 'svc-pest-3',
    categoryId: 'pest-control',
    name: 'Complete Termite Defense System',
    description: 'Soil injection + wood treatment with Termidor (Fipronil) for long-lasting protection against subterranean termites.',
    price: 2499,
    originalPrice: 3999,
    rating: 4.89,
    reviews: 1430,
    badge: 'Long-Term',
    estimatedDurationMinutes: 120,
    imageUrl: 'https://images.unsplash.com/photo-1584483766114-2cea6facdf57?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Soil injection treatment', 'Wood borate application', 'Entry point sealing', '5-year protection guarantee'],
    exclusions: ['Structural timber repair'],
    isActive: true,
  },
  {
    id: 'svc-pest-4',
    categoryId: 'pest-control',
    name: 'Mosquito & Fly Indoor Fogging',
    description: 'Cold fogging with WHO-approved Deltamethrin for complete knockdown of mosquitoes, houseflies, and flying insects.',
    price: 599,
    originalPrice: 999,
    rating: 4.82,
    reviews: 3210,
    badge: 'Seasonal',
    estimatedDurationMinutes: 30,
    imageUrl: 'https://images.unsplash.com/photo-1584483766114-2cea6facdf57?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Cold fog application', 'Entry point spray', 'Food-safe chemicals', '30-day guarantee'],
    exclusions: ['Outdoor garden fogging'],
    isActive: true,
  },

  // ── APPLIANCE REPAIR ─────────────────────────────────────────────────────────
  {
    id: 'svc-app-1',
    categoryId: 'appliance-repair',
    name: 'Washing Machine Drum & Motor Repair',
    description: 'Inspection and fix for front/top load washers: drain error, heavy vibration, spin cycle failure, inlet valve clog.',
    price: 449,
    originalPrice: 799,
    rating: 4.85,
    reviews: 3120,
    badge: 'Popular',
    estimatedDurationMinutes: 60,
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Drain pump test', 'Belt tension adjustment', 'Motor capacitor test', '30-day warranty'],
    exclusions: ['Cost of main motherboard PCB'],
    isActive: true,
  },
  {
    id: 'svc-app-2',
    categoryId: 'appliance-repair',
    name: 'Refrigerator Cooling & Thermostat Repair',
    description: 'Fix poor cooling, unusual noise, ice buildup, door seal failure, and thermostat/PCB faults in single/double door fridges.',
    price: 499,
    originalPrice: 899,
    rating: 4.83,
    reviews: 2540,
    badge: 'Quick Fix',
    estimatedDurationMinutes: 60,
    imageUrl: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Temperature diagnostics', 'Door seal replacement', 'Defrost timer check', '30-day warranty'],
    exclusions: ['Compressor gas recharge'],
    isActive: true,
  },
  {
    id: 'svc-app-3',
    categoryId: 'appliance-repair',
    name: 'Microwave Oven Heating & Magnetron Fix',
    description: 'Diagnose and repair microwave not heating, turntable error, sparking, fuse blown, and control panel failures.',
    price: 399,
    originalPrice: 699,
    rating: 4.81,
    reviews: 1670,
    badge: 'Specialist',
    estimatedDurationMinutes: 45,
    imageUrl: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Magnetron output test', 'Door switch check', 'Fuse & capacitor test', '30-day warranty'],
    exclusions: ['New magnetron tube cost'],
    isActive: true,
  },
  {
    id: 'svc-app-4',
    categoryId: 'appliance-repair',
    name: 'Water Purifier RO Filter Service & TDS',
    description: 'Complete 5-stage RO membrane check, sediment/carbon filter cartridge change, TDS meter calibration, and sanitization.',
    price: 499,
    originalPrice: 849,
    rating: 4.88,
    reviews: 4210,
    badge: 'Most Booked',
    estimatedDurationMinutes: 60,
    imageUrl: 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?auto=format&fit=crop&w=800&q=80',
    inclusions: ['TDS inlet/outlet measurement', 'Sediment filter change', 'Carbon filter change', 'Tank sanitization', '30-day warranty'],
    exclusions: ['RO membrane replacement cost'],
    isActive: true,
  },

  // ── GARDENING ─────────────────────────────────────────────────────────────────
  {
    id: 'svc-gard-1',
    categoryId: 'gardening',
    name: 'Lawn Mowing & Hedge Trimming',
    description: 'Professional grass edging, electric mower trim, shrub shaping, weed clearing, and leaf composting cleanup.',
    price: 499,
    originalPrice: 899,
    rating: 4.84,
    reviews: 1890,
    badge: 'Popular',
    estimatedDurationMinutes: 90,
    imageUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Lawn height leveling', 'Hedge shaping', 'Weeding & dry debris disposal', '30-day warranty'],
    exclusions: ['Purchase of ornamental plants'],
    isActive: true,
  },
  {
    id: 'svc-gard-2',
    categoryId: 'gardening',
    name: 'Plant Repotting & Organic Fertilizer',
    description: 'Re-pot up to 10 plants with fresh cocopeat/perlite mix, root pruning, slow-release organic fertilizer application.',
    price: 399,
    originalPrice: 699,
    rating: 4.80,
    reviews: 1120,
    badge: 'Plant Care',
    estimatedDurationMinutes: 60,
    imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Fresh potting mix', 'Root inspection', 'Organic fertilizer', 'Pest spray on foliage', '30-day warranty'],
    exclusions: ['Cost of new pots'],
    isActive: true,
  },
  {
    id: 'svc-gard-3',
    categoryId: 'gardening',
    name: 'Balcony Garden Setup & Drip Irrigation',
    description: 'Design and install a custom balcony kitchen garden with raised planter bags, drip irrigation timer, and seed sowing.',
    price: 899,
    originalPrice: 1499,
    rating: 4.86,
    reviews: 680,
    badge: 'Premium Setup',
    estimatedDurationMinutes: 120,
    imageUrl: 'https://images.unsplash.com/photo-1592150621744-aca64f48394a?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Planter bag installation', 'Drip irrigation layout', 'Seed/sapling planting', 'Care instruction card', '30-day warranty'],
    exclusions: ['Cost of planters & seeds'],
    isActive: true,
  },
  {
    id: 'svc-gard-4',
    categoryId: 'gardening',
    name: 'Garden Pest Spray & Soil De-Weeding',
    description: 'Neem oil + bio-pesticide spray for aphids, mealybugs, and fungal diseases, plus manual de-weeding of garden beds.',
    price: 449,
    originalPrice: 749,
    rating: 4.82,
    reviews: 940,
    badge: 'Plant Health',
    estimatedDurationMinutes: 60,
    imageUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Neem oil spray', 'Manual de-weeding', 'Soil aeration', '30-day plant health warranty'],
    exclusions: ['Cost of chemical pesticides'],
    isActive: true,
  },

  // ── LOCKSMITH ─────────────────────────────────────────────────────────────────
  {
    id: 'svc-lock-1',
    categoryId: 'locksmith',
    name: 'Emergency Door Lockout Opening',
    description: 'Fast damage-free entry for locked wooden, metal, or glass doors when keys are lost or locked inside.',
    price: 499,
    originalPrice: 799,
    rating: 4.88,
    reviews: 4320,
    badge: 'Emergency',
    estimatedDurationMinutes: 30,
    imageUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Non-destructive opening tools', 'Latch inspection', 'Immediate dispatch', '30-day warranty'],
    exclusions: ['New lock replacement'],
    isActive: true,
  },
  {
    id: 'svc-lock-2',
    categoryId: 'locksmith',
    name: 'Smart Digital Door Lock Fitting',
    description: 'Installation and programming of fingerprint, PIN, or card-access smart locks on wooden, metal, or glass doors.',
    price: 899,
    originalPrice: 1499,
    rating: 4.87,
    reviews: 1870,
    badge: 'Smart Home',
    estimatedDurationMinutes: 60,
    imageUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Door measurement & drilling', 'Lock hardware fitting', 'Fingerprint/PIN programming', '30-day warranty'],
    exclusions: ['Cost of smart lock unit'],
    isActive: true,
  },
  {
    id: 'svc-lock-3',
    categoryId: 'locksmith',
    name: 'Deadbolt Lock Replacement & Key Duplication',
    description: 'Replace old cylinder deadbolt with high-security Godrej/Yale lock, and duplicate up to 3 new keys on site.',
    price: 399,
    originalPrice: 649,
    rating: 4.83,
    reviews: 2140,
    badge: 'Security',
    estimatedDurationMinutes: 30,
    imageUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Cylinder replacement', 'Strike plate alignment', '3 key duplication', '30-day warranty'],
    exclusions: ['Cost of lock body'],
    isActive: true,
  },
  {
    id: 'svc-lock-4',
    categoryId: 'locksmith',
    name: 'Sliding Balcony Lock & Latch Replacement',
    description: 'Fix or replace worn sliding door/window latches, crescent locks, and multi-point locking bars.',
    price: 349,
    originalPrice: 599,
    rating: 4.79,
    reviews: 980,
    badge: 'Quick Fix',
    estimatedDurationMinutes: 30,
    imageUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Latch mechanism replacement', 'Track alignment', 'Lubrication', '30-day warranty'],
    exclusions: ['Full window frame replacement'],
    isActive: true,
  },

  // ── WATER TANK CLEANING ───────────────────────────────────────────────────────
  {
    id: 'svc-tank-1',
    categoryId: 'water-tank-cleaning',
    name: 'Overhead Tank Deep Cleaning & UV Sanitization',
    description: '6-stage mechanized cleaning: sludge dewatering, high pressure rotary jet wash, vacuuming, antibacterial spray, and UV treatment.',
    price: 799,
    originalPrice: 1299,
    rating: 4.90,
    reviews: 2870,
    badge: 'Best Seller',
    estimatedDurationMinutes: 90,
    imageUrl: 'https://images.unsplash.com/photo-1542013936693-884638332954?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Submersible pump sludge extraction', 'High pressure wall jetting', 'UV antibacterial radiation', '60-day purity guarantee'],
    exclusions: ['Plumbing valve replacement'],
    isActive: true,
  },
  {
    id: 'svc-tank-2',
    categoryId: 'water-tank-cleaning',
    name: 'Underground Sump High Pressure Sludge Wash',
    description: 'Dewatering, sludge extraction, high-pressure rotary jetting, and chemical disinfection of underground sumps.',
    price: 1299,
    originalPrice: 1999,
    rating: 4.87,
    reviews: 1540,
    badge: 'Industrial Grade',
    estimatedDurationMinutes: 120,
    imageUrl: 'https://images.unsplash.com/photo-1542013936693-884638332954?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Sump dewatering pump', 'High-pressure rotary jetter', 'Chemical disinfection', '60-day guarantee'],
    exclusions: ['Sump structural repairs'],
    isActive: true,
  },
  {
    id: 'svc-tank-3',
    categoryId: 'water-tank-cleaning',
    name: 'Complete Dual Tank Combo (Overhead + Sump)',
    description: 'Full cleaning of both overhead and underground tanks for complete water hygiene at a bundled price.',
    price: 1799,
    originalPrice: 2999,
    rating: 4.91,
    reviews: 1020,
    badge: 'Combo Deal',
    estimatedDurationMinutes: 180,
    imageUrl: 'https://images.unsplash.com/photo-1542013936693-884638332954?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Both tank cleaning', 'UV sanitization', 'TDS check post-cleaning', '90-day guarantee'],
    exclusions: ['Pump repair or replacement'],
    isActive: true,
  },
  {
    id: 'svc-tank-4',
    categoryId: 'water-tank-cleaning',
    name: 'Society / Apartment Multi-Tank Package',
    description: 'Bulk discount cleaning for housing society overhead + underground water storage tanks with compliance certificate.',
    price: 2999,
    originalPrice: 4999,
    rating: 4.88,
    reviews: 420,
    badge: 'Society Plan',
    estimatedDurationMinutes: 240,
    imageUrl: 'https://images.unsplash.com/photo-1542013936693-884638332954?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Up to 4 tanks included', 'Compliance certificate', 'Water quality report', '90-day guarantee'],
    exclusions: ['Tanks beyond 4 (additional charge)'],
    isActive: true,
  },

  // ── GENERAL HOME REPAIRS ──────────────────────────────────────────────────────
  {
    id: 'svc-handy-1',
    categoryId: 'general-home-repairs',
    name: 'Handyman Drill & Hang (TV, Mirror, Curtains)',
    description: 'Precision drill holes with dust collector: TV wall bracket, mirror, paintings, curtain rods, clocks, and bathroom fixtures.',
    price: 299,
    originalPrice: 499,
    rating: 4.86,
    reviews: 4210,
    badge: 'Best Seller',
    estimatedDurationMinutes: 45,
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Heavy-duty wall anchors', 'Laser level alignment', 'Up to 3 items hung', '30-day warranty'],
    exclusions: ['Cost of heavy TV bracket'],
    isActive: true,
  },
  {
    id: 'svc-handy-2',
    categoryId: 'general-home-repairs',
    name: 'Glass / Shelf Silicon Sealing & Touch-Ups',
    description: 'Waterproof silicon beading for shower enclosures, kitchen counter edges, glass panels, and bathroom fittings.',
    price: 349,
    originalPrice: 599,
    rating: 4.82,
    reviews: 1870,
    badge: 'Waterproof',
    estimatedDurationMinutes: 45,
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Old silicon removal', 'Surface cleaning', 'New silicon bead', 'Curing inspection', '30-day warranty'],
    exclusions: ['Glass panel replacement'],
    isActive: true,
  },
  {
    id: 'svc-handy-3',
    categoryId: 'general-home-repairs',
    name: 'Curtain Rod & Blind Installation',
    description: 'Install single/double curtain tracks, Roman blinds, roller blinds, or Venetian blinds with precision leveling.',
    price: 249,
    originalPrice: 449,
    rating: 4.84,
    reviews: 2130,
    badge: 'Popular',
    estimatedDurationMinutes: 30,
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Wall bracket drilling', 'Rod/track level mounting', 'Curtain hook hanging', '30-day warranty'],
    exclusions: ['Curtain or blind purchase'],
    isActive: true,
  },
  {
    id: 'svc-handy-4',
    categoryId: 'general-home-repairs',
    name: 'Bathroom Hardware & Mirror Mounting',
    description: 'Fit towel bars, soap dishes, toilet paper holders, robe hooks, and frameless bathroom mirrors with silicon seal.',
    price: 299,
    originalPrice: 499,
    rating: 4.81,
    reviews: 1540,
    badge: 'Quick Fix',
    estimatedDurationMinutes: 30,
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80',
    inclusions: ['Anchor drilling (tile safe)', 'Hardware installation', 'Silicon mirror seal', '30-day warranty'],
    exclusions: ['Bathroom accessories purchase'],
    isActive: true,
  },
];

export async function getCategories(): Promise<Category[]> {
  try {
    const { data } = await apiClient.get('/categories');
    return Array.isArray(data) && data.length ? data : MOCK_CATEGORIES;
  } catch {
    return MOCK_CATEGORIES;
  }
}

export async function getServices(): Promise<Service[]> {
  try {
    const { data } = await apiClient.get('/services');
    return Array.isArray(data) && data.length ? data : MOCK_SERVICES;
  } catch {
    return MOCK_SERVICES;
  }
}

export async function getServicesByCategory(categoryId: string): Promise<Service[]> {
  try {
    const { data } = await apiClient.get('/services', { params: { categoryId } });
    if (Array.isArray(data) && data.length) return data;
    return MOCK_SERVICES.filter((s) => s.categoryId === categoryId || categoryId === 'all');
  } catch {
    const list = MOCK_SERVICES.filter((s) => s.categoryId === categoryId);
    return list.length ? list : MOCK_SERVICES;
  }
}

export async function searchServices(query: string): Promise<Service[]> {
  try {
    const { data } = await apiClient.get('/services/search', { params: { q: query } });
    return Array.isArray(data) ? data : MOCK_SERVICES;
  } catch {
    const q = query.toLowerCase();
    return MOCK_SERVICES.filter(
      (s) => s.name.toLowerCase().includes(q) || s.description.toLowerCase().includes(q)
    );
  }
}

export async function getServiceById(id: string): Promise<Service> {
  try {
    const { data } = await apiClient.get(`/services/${id}`);
    return data ?? MOCK_SERVICES[0];
  } catch {
    return MOCK_SERVICES.find((s) => s.id === id) ?? MOCK_SERVICES[0];
  }
}
